/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.manex.andaman7.injector.views;

import biz.manex.andaman7.injector.controllers.MainController;
import biz.manex.andaman7.injector.models.Settings;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.Properties;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Pierre-Yves
 */
public class LoginFrame extends javax.swing.JFrame {

    private final MainController mainController;
    private Settings settings;

    /**
     * Creates new form LoginFrame
     * @param mainController the controller that will control the frame
     * @param loginListener the listener that will listen for actions on the
     *                      login button
     */
    public LoginFrame(MainController mainController, ActionListener loginListener, Properties properties) {
        initComponents();

        this.mainController = mainController;

        this.jButtonLogin.addActionListener(loginListener);

        jTextFieldSettingsServerPort.setText(properties.getProperty("serverPort"));
        jTextFieldSettingsServerHostname.setText(properties.getProperty("serverHostname"));
        jTextFieldSettingsApiKey.setText(properties.getProperty("apiKey"));

        jTextFieldSettingsUsername.setText(properties.getProperty("username"));
        jPasswordFieldSettingsPassword.setText(properties.getProperty("password"));

        if(jTextFieldSettingsServerPort.getText().equals("443")) {
            jComboBoxProtocol.setSelectedItem("https");
        }
        else {
            jComboBoxProtocol.setSelectedItem("http");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSettingsUser = new javax.swing.JPanel();
        jLabelSettingsUsername = new javax.swing.JLabel();
        jTextFieldSettingsUsername = new javax.swing.JTextField();
        jLabelSettingsPassword = new javax.swing.JLabel();
        jPasswordFieldSettingsPassword = new javax.swing.JPasswordField();
        jLabelSettingTestConnection = new javax.swing.JLabel();
        jPanelSettingsServer = new javax.swing.JPanel();
        jLabelSettingsServerHostname = new javax.swing.JLabel();
        jTextFieldSettingsServerHostname = new javax.swing.JTextField();
        jLabelSettingsServerPort = new javax.swing.JLabel();
        jTextFieldSettingsServerPort = new javax.swing.JTextField();
        jLabelSettingsApiKey = new javax.swing.JLabel();
        jTextFieldSettingsApiKey = new javax.swing.JTextField();
        jLabelProtocol = new javax.swing.JLabel();
        jComboBoxProtocol = new javax.swing.JComboBox();
        jButtonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelSettingsUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));

        jLabelSettingsUsername.setText("Username");

        jTextFieldSettingsUsername.setInputVerifier(new NoEmptyInputVerifier());
        jTextFieldSettingsUsername.setName("username"); // NOI18N
        jTextFieldSettingsUsername.setPreferredSize(new java.awt.Dimension(125, 22));

        jLabelSettingsPassword.setText("Password");

        jPasswordFieldSettingsPassword.setInputVerifier(new NoEmptyInputVerifier());
        jPasswordFieldSettingsPassword.setName("password"); // NOI18N
        jPasswordFieldSettingsPassword.setPreferredSize(new java.awt.Dimension(125, 22));

        javax.swing.GroupLayout jPanelSettingsUserLayout = new javax.swing.GroupLayout(jPanelSettingsUser);
        jPanelSettingsUser.setLayout(jPanelSettingsUserLayout);
        jPanelSettingsUserLayout.setHorizontalGroup(
            jPanelSettingsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsUserLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabelSettingTestConnection))
                    .addGroup(jPanelSettingsUserLayout.createSequentialGroup()
                        .addGroup(jPanelSettingsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSettingsUsername)
                            .addComponent(jLabelSettingsPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSettingsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSettingsUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldSettingsPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSettingsUserLayout.setVerticalGroup(
            jPanelSettingsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsUserLayout.createSequentialGroup()
                .addGroup(jPanelSettingsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSettingsUsername)
                    .addComponent(jTextFieldSettingsUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSettingsPassword)
                    .addComponent(jPasswordFieldSettingsPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSettingTestConnection)
                .addContainerGap())
        );

        jPanelSettingsServer.setBorder(javax.swing.BorderFactory.createTitledBorder("Server"));

        jLabelSettingsServerHostname.setText("Server hostname");

        jTextFieldSettingsServerHostname.setInputVerifier(new NoEmptyInputVerifier());
        jTextFieldSettingsServerHostname.setName("server hostname"); // NOI18N

        jLabelSettingsServerPort.setText("Server port");

        jTextFieldSettingsServerPort.setInputVerifier(new NoEmptyInputVerifier());
        jTextFieldSettingsServerPort.setName("server port"); // NOI18N
        jTextFieldSettingsServerPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSettingsServerPortKeyReleased(evt);
            }
        });

        jLabelSettingsApiKey.setText("API key");

        jTextFieldSettingsApiKey.setInputVerifier(new NoEmptyInputVerifier());
        jTextFieldSettingsApiKey.setName("API key"); // NOI18N

        jLabelProtocol.setText("Protocol");

        jComboBoxProtocol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "http", "https" }));

        javax.swing.GroupLayout jPanelSettingsServerLayout = new javax.swing.GroupLayout(jPanelSettingsServer);
        jPanelSettingsServer.setLayout(jPanelSettingsServerLayout);
        jPanelSettingsServerLayout.setHorizontalGroup(
            jPanelSettingsServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSettingsServerHostname)
                    .addComponent(jLabelSettingsApiKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSettingsApiKey, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jTextFieldSettingsServerHostname))
                .addGap(18, 18, 18)
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSettingsServerLayout.createSequentialGroup()
                        .addComponent(jLabelSettingsServerPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSettingsServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSettingsServerLayout.createSequentialGroup()
                        .addComponent(jLabelProtocol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelSettingsServerLayout.setVerticalGroup(
            jPanelSettingsServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsServerLayout.createSequentialGroup()
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSettingsServerHostname)
                    .addComponent(jTextFieldSettingsServerHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSettingsServerPort)
                    .addComponent(jTextFieldSettingsServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSettingsApiKey)
                    .addComponent(jTextFieldSettingsApiKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProtocol)
                    .addComponent(jComboBoxProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonLogin.setText("Login");
        jButtonLogin.setName("login"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSettingsUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSettingsServer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLogin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSettingsServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSettingsUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButtonLogin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSettingsServerPortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSettingsServerPortKeyReleased
        if(jTextFieldSettingsServerPort.getText().equals("443"))
            jComboBoxProtocol.setSelectedItem("https");
    }//GEN-LAST:event_jTextFieldSettingsServerPortKeyReleased

    private boolean verifySettings() {
        
        boolean state = verifyForm(jPanelSettingsServer);
        
        if(state)
            state = verifyForm(jPanelSettingsUser);
        
        return state;
    }
    
    private boolean verifyForm(JComponent form) {
        
        for(Component item : Arrays.asList(form.getComponents())) {
            
            JComponent component = (JComponent) item;
            InputVerifier iv = component.getInputVerifier();
            
            if(iv != null && !iv.verify(component)) {
                JOptionPane.showMessageDialog(this,
                        "The " + item.getName() + " must not be empty. Check the settings tab.",
                        "Missing setting", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        
        return true;
    }
    
    public Settings getSettings() {

        if(verifySettings()) {
            
            String apiKey = jTextFieldSettingsApiKey.getText();
            String serverHostname = jTextFieldSettingsServerHostname.getText();
            String serverPort = jTextFieldSettingsServerPort.getText();
            String username = jTextFieldSettingsUsername.getText();
            String password = new String(jPasswordFieldSettingsPassword.getPassword());
            
            boolean isHttps = false;
            
            if(jComboBoxProtocol.getSelectedItem().toString().equals("https"))
                isHttps = true;

            Settings settings = new Settings();
            settings.setApiKey(apiKey);
            settings.setServerHostname(serverHostname);
            settings.setServerPort(serverPort);
            settings.setUsername(username);
            settings.setPassword(password);
            settings.setHttps(isHttps);
            
            return settings;
        }
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox jComboBoxProtocol;
    private javax.swing.JLabel jLabelProtocol;
    private javax.swing.JLabel jLabelSettingTestConnection;
    private javax.swing.JLabel jLabelSettingsApiKey;
    private javax.swing.JLabel jLabelSettingsPassword;
    private javax.swing.JLabel jLabelSettingsServerHostname;
    private javax.swing.JLabel jLabelSettingsServerPort;
    private javax.swing.JLabel jLabelSettingsUsername;
    private javax.swing.JPanel jPanelSettingsServer;
    private javax.swing.JPanel jPanelSettingsUser;
    private javax.swing.JPasswordField jPasswordFieldSettingsPassword;
    private javax.swing.JTextField jTextFieldSettingsApiKey;
    private javax.swing.JTextField jTextFieldSettingsServerHostname;
    private javax.swing.JTextField jTextFieldSettingsServerPort;
    private javax.swing.JTextField jTextFieldSettingsUsername;
    // End of variables declaration//GEN-END:variables
}
