package biz.manex.andaman7.injector.views;

import biz.manex.andaman7.injector.models.Settings;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.Properties;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.InputVerifier;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;

/**
 * The login GUI frame.
 *
 * @author Pierre-Yves (pierreyves.derbaix@gmail.com)<br/>
 * Copyright A7 Software (http://a7-software.com/)<br/>
 * Date : 06/02/2015.<br/>
 */
public class LoginFrame extends JFrame {

    /**
     * Creates new form LoginFrame
     * @param loginListener the listener that will listen for actions on the
     *                      login button
     * @param properties the properties used to pre-fill the login form
     */
    public LoginFrame(ActionListener loginListener, Properties properties) {
        initComponents();

        jButtonLogin.addActionListener(loginListener);

        jTextFieldSettingsServerPort.setText(properties.getProperty("serverPort"));
        jTextFieldSettingsServerHostname.setText(properties.getProperty("serverHostname"));
        jTextFieldSettingsApiKey.setText(properties.getProperty("apiKey"));

        jTextFieldSettingsUsername.setText(properties.getProperty("username"));
        jPasswordFieldSettingsPassword.setText(properties.getProperty("password"));

        if(jTextFieldSettingsServerPort.getText().equals("443")) {
            jComboBoxProtocol.setSelectedItem("https");
        }
        else {
            jComboBoxProtocol.setSelectedItem("http");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSettingsUser = new JPanel();
        jLabelSettingsUsername = new JLabel();
        jTextFieldSettingsUsername = new JTextField();
        jLabelSettingsPassword = new JLabel();
        jPasswordFieldSettingsPassword = new JPasswordField();
        jLabelSettingTestConnection = new JLabel();
        jPanelSettingsServer = new JPanel();
        jLabelSettingsServerHostname = new JLabel();
        jTextFieldSettingsServerHostname = new JTextField();
        jLabelSettingsServerPort = new JLabel();
        jTextFieldSettingsServerPort = new JTextField();
        jLabelSettingsApiKey = new JLabel();
        jTextFieldSettingsApiKey = new JTextField();
        jLabelProtocol = new JLabel();
        jComboBoxProtocol = new JComboBox();
        jButtonLogin = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelSettingsUser.setBorder(BorderFactory.createTitledBorder("User"));

        jLabelSettingsUsername.setText("Username");

        jTextFieldSettingsUsername.setInputVerifier(new NoEmptyInputVerifier());
        jTextFieldSettingsUsername.setName("username"); // NOI18N
        jTextFieldSettingsUsername.setPreferredSize(new Dimension(125, 22));

        jLabelSettingsPassword.setText("Password");

        jPasswordFieldSettingsPassword.setInputVerifier(new NoEmptyInputVerifier());
        jPasswordFieldSettingsPassword.setName("password"); // NOI18N
        jPasswordFieldSettingsPassword.setPreferredSize(new Dimension(125, 22));

        GroupLayout jPanelSettingsUserLayout = new GroupLayout(jPanelSettingsUser);
        jPanelSettingsUser.setLayout(jPanelSettingsUserLayout);
        jPanelSettingsUserLayout.setHorizontalGroup(
            jPanelSettingsUserLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelSettingsUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsUserLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanelSettingsUserLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabelSettingTestConnection))
                    .addGroup(jPanelSettingsUserLayout.createSequentialGroup()
                        .addGroup(jPanelSettingsUserLayout.createParallelGroup(Alignment.LEADING)
                            .addComponent(jLabelSettingsUsername)
                            .addComponent(jLabelSettingsPassword))
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSettingsUserLayout.createParallelGroup(Alignment.LEADING, false)
                            .addComponent(jTextFieldSettingsUsername, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldSettingsPassword, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSettingsUserLayout.setVerticalGroup(
            jPanelSettingsUserLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelSettingsUserLayout.createSequentialGroup()
                .addGroup(jPanelSettingsUserLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabelSettingsUsername)
                    .addComponent(jTextFieldSettingsUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsUserLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabelSettingsPassword)
                    .addComponent(jPasswordFieldSettingsPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSettingTestConnection)
                .addContainerGap())
        );

        jPanelSettingsServer.setBorder(BorderFactory.createTitledBorder("Server"));

        jLabelSettingsServerHostname.setText("Server hostname");

        jTextFieldSettingsServerHostname.setInputVerifier(new NoEmptyInputVerifier());
        jTextFieldSettingsServerHostname.setName("server hostname"); // NOI18N

        jLabelSettingsServerPort.setText("Server port");

        jTextFieldSettingsServerPort.setInputVerifier(new NoEmptyInputVerifier());
        jTextFieldSettingsServerPort.setName("server port"); // NOI18N
        jTextFieldSettingsServerPort.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                jTextFieldSettingsServerPortKeyReleased(evt);
            }
        });

        jLabelSettingsApiKey.setText("API key");

        jTextFieldSettingsApiKey.setInputVerifier(new NoEmptyInputVerifier());
        jTextFieldSettingsApiKey.setName("API key"); // NOI18N

        jLabelProtocol.setText("Protocol");

        jComboBoxProtocol.setModel(new DefaultComboBoxModel(new String[] { "http", "https" }));

        GroupLayout jPanelSettingsServerLayout = new GroupLayout(jPanelSettingsServer);
        jPanelSettingsServer.setLayout(jPanelSettingsServerLayout);
        jPanelSettingsServerLayout.setHorizontalGroup(
            jPanelSettingsServerLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelSettingsServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jLabelSettingsServerHostname)
                    .addComponent(jLabelSettingsApiKey))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jTextFieldSettingsApiKey, GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jTextFieldSettingsServerHostname))
                .addGap(18, 18, 18)
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(Alignment.TRAILING)
                    .addGroup(jPanelSettingsServerLayout.createSequentialGroup()
                        .addComponent(jLabelSettingsServerPort)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSettingsServerPort, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSettingsServerLayout.createSequentialGroup()
                        .addComponent(jLabelProtocol)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxProtocol, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelSettingsServerLayout.setVerticalGroup(
            jPanelSettingsServerLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelSettingsServerLayout.createSequentialGroup()
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabelSettingsServerHostname)
                    .addComponent(jTextFieldSettingsServerHostname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSettingsServerPort)
                    .addComponent(jTextFieldSettingsServerPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsServerLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabelSettingsApiKey)
                    .addComponent(jTextFieldSettingsApiKey, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProtocol)
                    .addComponent(jComboBoxProtocol, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonLogin.setText("Login");
        jButtonLogin.setName("login"); // NOI18N

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jPanelSettingsUser, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSettingsServer, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLogin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSettingsServer, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSettingsUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButtonLogin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Listens for a key to be pressed when focusing the server port text field
     *
     * @param evt the key event
     */
    private void jTextFieldSettingsServerPortKeyReleased(KeyEvent evt) {//GEN-FIRST:event_jTextFieldSettingsServerPortKeyReleased
        if(jTextFieldSettingsServerPort.getText().equals("443"))
            jComboBoxProtocol.setSelectedItem("https");
    }//GEN-LAST:event_jTextFieldSettingsServerPortKeyReleased

    /**
     * Verifies if no value of the settings is empty.
     *
     * @return {@code true} if the settings are all initialized, {@code false} otherwise
     */
    private boolean verifySettings() {
        
        boolean state = verifyForm(jPanelSettingsServer);
        
        if(state)
            state = verifyForm(jPanelSettingsUser);
        
        return state;
    }

    /**
     * Verifies a form.
     * @param form the form to verify
     * @return {@code true} if all the values of the form are coherent, {@code false} otherwise
     */
    private boolean verifyForm(JComponent form) {
        
        for(Component item : Arrays.asList(form.getComponents())) {
            
            JComponent component = (JComponent) item;
            InputVerifier iv = component.getInputVerifier();
            
            if((iv != null) && (!iv.verify(component))) {
                JOptionPane.showMessageDialog(this,
                        "The " + item.getName() + " must not be empty. Check the settings tab.",
                        "Missing setting", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        
        return true;
    }

    /**
     * Returns the {@link biz.manex.andaman7.injector.models.Settings} according to the form.
     *
     * @return the {@link biz.manex.andaman7.injector.models.Settings}
     * @see biz.manex.andaman7.injector.models.Settings
     */
    public Settings getSettings() {

        if(verifySettings()) {
            
            String apiKey = jTextFieldSettingsApiKey.getText();
            String serverHostname = jTextFieldSettingsServerHostname.getText();
            String serverPort = jTextFieldSettingsServerPort.getText();
            String username = jTextFieldSettingsUsername.getText();
            String password = new String(jPasswordFieldSettingsPassword.getPassword());
            
            boolean isHttps = false;
            
            if(jComboBoxProtocol.getSelectedItem().toString().equals("https"))
                isHttps = true;

            Settings settings = new Settings();
            settings.setApiKey(apiKey);
            settings.setServerHostname(serverHostname);
            settings.setServerPort(serverPort);
            settings.setUsername(username);
            settings.setPassword(password);
            settings.setHttps(isHttps);
            
            return settings;
        }
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonLogin;
    private JComboBox jComboBoxProtocol;
    private JLabel jLabelProtocol;
    private JLabel jLabelSettingTestConnection;
    private JLabel jLabelSettingsApiKey;
    private JLabel jLabelSettingsPassword;
    private JLabel jLabelSettingsServerHostname;
    private JLabel jLabelSettingsServerPort;
    private JLabel jLabelSettingsUsername;
    private JPanel jPanelSettingsServer;
    private JPanel jPanelSettingsUser;
    private JPasswordField jPasswordFieldSettingsPassword;
    private JTextField jTextFieldSettingsApiKey;
    private JTextField jTextFieldSettingsServerHostname;
    private JTextField jTextFieldSettingsServerPort;
    private JTextField jTextFieldSettingsUsername;
    // End of variables declaration//GEN-END:variables
}
